name: CI Pipeline

on:
  push:
    branches:
      - kai_dev
  pull_request:
    branches:
      - kai_dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from your repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.14.0' # Use the desired Node.js version

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install

    - name: Install Redis
      run: |
        sudo apt-get update
        sudo apt-get install redis-server -y
        sudo systemctl start redis-server        

    - name: Run server tests
      run: |
        npm run test_backend
