name: CI Pipeline

on:
  push:
    branches:
      - kai_dev
  pull_request:
    branches:
      - kai_dev

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   redis:
    #     image: redis:alpine
    #     ports:
    #       - 6378:6379    

    steps:
    # Checkout the code from your repo
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "REDIS_HOST=redis" >> $GITHUB_ENV
        echo "REDIS_PORT=6379" >> $GITHUB_ENV

    - name: Build and run tests with Docker Compose
      run: |
        docker compose up --abort-on-container-exit --exit-code-from tests
    
    - name: Clean up Docker
      run: |
        docker compose down
